### PR TITLE
[#737] Classic sheet text pdf bugs

### LINKED ISSUE #737: Text alignment issue with PDF Export for some abilities
**Describe the bug**
Abilities with longer text descriptions overlap after exporting them to PDF. The abilities display fine in classic view but are out of alignment when using Export as PDF or Export as PDF (High Res) causing text to overlap. 

Tested with A4 & Letter, Portrait and landscape

**To Reproduce**
1. Go to Heroes,  
2. Click on Classic View, Export as PDF
3. Save the File
4. Open the Exported PDF

**Expected behavior**
The abilities should display the same in classic view before and after export to pdf

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome,  Brave
 - Version Chrome (142.0.7444.176), Brave (v1.84.141 (Nov 18, 2025)

**Additional context**

**Classic View**
Image

**Exported PDF**
Image

**Classic View**
Image

**Exported PDF**
Image

**Exported PDF File Example**
[Jasmala (1).pdf](https://github.com/user-attachments/files/23796886/Jasmala.1.pdf)

### PR DESCRIPTION
**Pull request by Veritas1000**
Fixes #737 

The root cause of this part of the issue appears to be me using block elements within `<ul>` and `<li>` tags. Switching to `<div>`s (thankfully I can still take advantage of the `column-count` css property) seems to have fixed the issue in my testing. 

I also added some additional edge case stuff for calculating Reference card sizes, as well as tweaking the display of the main Characteristics

### CODE REVIEW

File: src/components/pages/heroes/hero-sheet/hero-sheet-preview-page.tsx [hunk 1]
```diff
@@ -240,6 +241,58 @@ export const HeroSheetPreviewPage = (props: Props) => {
 		}
 	};
 
+	/* eslint-disable @typescript-eslint/no-explicit-any */
```
Comment (Veritas1000) [inline src/components/pages/heroes/hero-sheet/hero-sheet-preview-page.tsx]: All of this stuff is some extra QoL stuff for my hero sheet preview/testing page to make it so I can render a single page at a time
